spring.application.name=tecback
spring.profiles.active=dev

logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.seu.pacote=DEBUG

spring.cache.type=simple
spring.cache.cache-names=genres